version: "3.8"

services:
  app:
    container_name: ms-yomaputra-betest
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    links:
      - mongodb
    depends_on:
      - mongodb
      - redis_yomaputra_betest
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - jenius-betest-network
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=app_user
      # - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=db_yomaputra_betest
    networks:
      - jenius-betest-network
  redis_yomaputra_betest:
    container_name: redis_yomaputra_betest
    image: redis:alpine3.18
    ports:
      - 6379:6379
    networks:
      - jenius-betest-network

networks:
  jenius-betest-network:
    driver: bridge